version: "3.9"

services:
  duckdock:
    build: duckdock
    #restart: unless-stopped
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    ports:
      - target: 5432
        published: 5050
        protocol: tcp
        mode: host
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

# volumes:
#   db-data:

